# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Linhua (Alex) WANG's Pages
email: linhuaw15213 (at) gmail (dot) com
description: >- # this means to ignore newlines until "baseurl:"
  Hi! Here is Alex's web page! I hope you like it! 
baseurl: "page" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: linhuaw_w
github_username:  linhuawang
#copyright: All contents in this blog are not for commerical purposes. Ideas/solutions might be borrowed/learned from other resources including `Stack Overflow`, `Wikipedia`, `Google`, other organizations and individuals. I very much appreciate your sharing of knowledge. Posts related to technical issues are only to avoid waste of time looking for solutions in my future study and research. I intentionally collect all info that are useful to me to my blog so that I can read later. I will cite the sources if they are from elsewhere and still avaliable. Please don't use for other purposes.
# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
